import type { Metadata } from "next";
import { CircleIcon } from "lucide-react";
import SignInOutText from "@/components/auth/sign-in-out-text";
export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen">
      <div className="flex w-full lg:w-1/2 flex-col px-8 sm:px-16 py-8">
        <div className="mt-6 mb-2 flex items-center gap-2 text-xl font-semibold">
          <CircleIcon className="h-8 w-8 fill-blue-600 text-white" />
          Invia
        </div>
        <SignInOutText />
        {children}
      </div>

      <div className="hidden lg:block lg:w-1/2 bg-gradient-to-br from-muted to-muted/75">
        <div className="">
          <h3 className="text-sm font-semibold text-muted-foreground absolute top-4 right-4">
            Stock Management
          </h3>
          <div className="absolute top-1/2 px-6 w-full">
            <div className="text-left max-w-md">
              <blockquote className="text-lg text-muted-foreground p-4 italic">
                &quot;Unlock the full potential of your business with our
                cutting-edge digital stock management tool. Streamline your
                operations, optimize inventory levels, and make data-driven
                decisions to boost profitability and stay ahead of the
                competition.&quot;
              </blockquote>
              <p className="text-xs text-muted-foreground px-4 pb-4">
                - Discover the power of digital stock management
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
