import type { Metadata } from "next";

import { BarChartIcon } from "@radix-ui/react-icons";

export const metadata: Metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen bg-background text-foreground">
      <div className="flex-1 flex flex-col items-center justify-center p-8 bg-background/80">
        <div className="text-2xl font-bold flex flex-col items-center">
          <BarChartIcon className="w-16 h-16 mb-4 text-primary" />
          <span className="text-primary">Invia</span>
        </div>
        <blockquote className="mt-8 text-xl text-center text-muted-foreground max-w-md">
          &quot;The stock market is a device for transferring money from the
          impatient to the patient.&quot;
          <footer className="mt-2 text-sm text-muted-foreground">
            — Warren Buffett
          </footer>
        </blockquote>
      </div>
      <div className="flex-1 flex items-center justify-center p-8">
        {children}
      </div>
    </div>
  );
}
